services:
  - type: web
    name: bhai-backend
    env: node
    buildCommand: cd bhai-backend && npm install
    startCommand: cd bhai-backend && node index.js
    envVars:
      - key: MONGO
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: IMAGE_KIT_ENDPOINT
        sync: false
      - key: IMAGE_KIT_PUBLIC_KEY
        sync: false
      - key: IMAGE_KIT_PRIVATE_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false

  - type: web
    name: bhai-frontend
    env: node
    buildCommand: cd client/bhai-frontend && npm install && npm run build
    startCommand: cd client/bhai-frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_IMAGE_KIT_ENDPOINT
        sync: false
      - key: VITE_IMAGE_KIT_PUBLIC_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_GEMINI_PUBLIC_KEY
        sync: false